config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "departments#index"
  
  get 'static_pages/home'
  get 'static_pages/about'
  root "static_pages#home"
	get "/about", to: "static_pages#about"

  resources :departments do
    resources :items 
  end
  
  resources :items do
      resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item

  before_save :check_author

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item

  # def new
  #   @comment = Comment.new
  # end
  def new
    @comment = Comment.new
    render partial: "form"
  end

  # def create
  #   @comment = @item.comments.new(comment_params)
  #   if @comment.save
  #     redirect_to department_item_path(@item.department_id, @topic)
  #   else
  #     render :new
  #   end
  # end
  def create
    @comment = @item.comments.new(comment_params)
    
    if @comment.save
      redirect_to department_items_path(@item.department_id, @comment)
    else
      render partial: "form"
    end
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:author, :body)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  # before_action :set_sub, except: [:index,:new, :create]
  # this ^^ does the same thing
  before_action :set_department, only: [:show, :edit, :update, :destroy]


  def index
    # render: index
    # happens automatically so dont need to write this
    @departments = Department.all
  end

  def show
    # render :show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to department_path(@department.id)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to department_path(@department.id)
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end
  

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    
    if @item.save
      redirect_to department_items_path(@department)
    else
      render partial: "form"
    end
  end

  def update
    if @item.update(item_params)
      redirect_to department_items_path(@department)
    else
      render partial: "form"
    end

  end

  def destroy
     @item.destroy
     redirect_to department_items_path(@department)
  end

  private 
  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:department_id])
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/comments/_form.html.erb
<h1> <%= @comment.id ? "Edit Comment for" : "Create Comment for" %> <%= @item.name %> </h1>
<!--  checks that @sub.id exists and if it does edit and if it doesnt new-->
<hr />
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous'%>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, require: true %>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/departments/_form.html.erb
<h1> <%= @department.id ? "Edit Department" : "Create Department" %> </h1>
<!--  checks that @department.id exists and if it does edit and if it doesnt new-->
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Click a Department To View Content</h1>
<%= link_to 'Create a new Department', new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name, department %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<% link_to 'View Department', department_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', department_path(@department.id), method: :delete %>
<br />
<%= link_to 'View Department Items', department_items_path(@department) %>
<br />
<%= link_to 'Add Items', new_department_item_path(@department) %>

app/views/items/_comment.html.erb
<hr/>
<p>Author: <%= @comment.author %></p>
<p><strong><%= @comment.body %></strong></p>
</hr>

app/views/items/_form.html.erb
<h1> <%= @item.id ? "Edit Item in" : "Create Item in" %> <%= @department.name %> </h1>
<!--  checks that @sub.id exists and if it does edit and if it doesnt new-->
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_area :price, require: true %>
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%= @department.name %> </h1>
<hr />
<h3>Click a Item To View Content</h3>
<%= link_to 'Create a new item', new_department_item_path %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>

app/views/items/show.html.erb
<h1><%= @department.name %> </h1>
<hr />
<p><%= @item.name %>: $<%= @item.price %></p>
<h3>Comments</h3>
<% @item.comments.each do |comment| %>
  <p>Author: <%= comment.author %></p>
  <p><u><%= comment.body %><u></p>
<% end %>

<hr />
<%= link_to 'Add Comment', new_item_comment_path(@item, @comment) %>
<%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<%= link_to 'Back To Items', department_items_path(@department) %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', static_pages_about_path %>
<%= link_to 'Departments', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1> About Page </h1>
<p>This app has department stores with items that you can edit, create new, and delete. COOL!</p>

app/views/static_pages/home.html.erb
<h1>Department Store Home Page</h1>

<p> ¯\_(ツ)_/¯ </p>

<%= link_to "Back to Departments", departments_path %> 